from collections import deque

stack = []
stack.append(1)
stack.append(2)
stack.append(3)
stack.append(4)
stack.append(5)
stack.pop()
stack.append(6)
stack.append(7)
stack.append(8)
stack.append(9)
stack.pop()
print(stack)
print(stack[::-1])

que = deque()
que.append(1)
que.append(2)
que.append(3)
que.append(4)
que.popleft()
que.append(5)
que.append(6)
que.append(7)
que.popleft()
print(que)
que.reverse()
print(type(que))